name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          # Linux iced build
          - os: ubuntu-latest
            file: pocket-ark-client
            file_name: Ubuntu Build
            feature: iced
          # Windows iced build
          - os: windows-latest
            file: pocket-ark-client.exe
            file_name: Windows Build
            feature: iced
          # Windows native build
          - os: windows-latest
            file: pocket-ark-client.exe
            file_name: Windows Native Build
            feature: native
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      # OpenSSL dependency on windows
      - name: Setup vcpkg
        run: vcpkg install openssl:x64-windows-static-md && vcpkg integrate install
        if: matrix.os == 'windows-latest'
      # Building
      - name: Build Client
        run: cargo build --verbose --no-default-features --features ${{ matrix.feature }}
      # Testing
      - name: Run tests
        run: cargo test --verbose --no-default-features --features ${{ matrix.feature }}
      # Uploading builds
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file_name }}
          path: "./target/debug/${{ matrix.file }}"
