name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
  VCPKGRS_DYNAMIC: 1
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            file: pocket-relay-client
            file_name: Ubuntu Build
          - os: windows-latest
            file: pocket-relay-client.exe
            file_name: Windows Build
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: openssl
          triplet: x64-windows-static
          token: ${{ github.token }}
        if: matrix.os == 'windows-latest'
      - name: Build Client
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file_name }}
          path: "./target/debug/${{ matrix.file }}"
